### PR TITLE
:ambulance: [#49] Save comments inside imports

### LINKED ISSUE #49: [IMRF-45] Save comments inside imports section
Single-commented lines which contains only comments inside import section like this one

```haskell
-- All text imports
import Data.Text (Text)
import qualified Data.Text as T
```

are preserved. Comments in any other forms are stripped.

### PR DESCRIPTION
**Pull request by kristoff3r**
Should fix #49 (if I have understood it correctly).

I'd like to add a test as well, but I can't figure out where in test-data it should go.

(P.S. sorry about the "referenced this issue" spam, force pushing to my fork with the issue number in the commit message apparently does horrible things to GitHub issues :/)

### CODE REVIEW

**Comment by ChShersh** [comment]
@kristoff3r First of all, thanks for spending your time to contribute to this project! I really appreciate your effort.

You understood the problem correctly. But you solution is partial. For example, comments like in this example will still be removed:

```haskell
import {- first example -} Foo
import Bar -- comment after import
```

Though your solution is already good enough so I can merge your PR after you add tests. Regarding tests:

1. First, run `stack test` to ensure that current tests are passing.
2. Create files with example in [`test-data` folder](https://github.com/serokell/importify/tree/master/test/test-data) with `.hs` extension.
3. Run `stack exec golden-generator`.
4. Verify manually new generated files with `.golden` extension.
5. Push if everything is ok.

**Comment by kristoff3r** [comment]
Ok, that sounds doable.

About the tests, I guess they should be placed in `base@basic`? I am a bit unclear about the precise seperation between which tests goes in `base@basic` vs the `importify@project` folder. It looks like base has the tests that nothing breaks, while importify has the tests that actually removes imports?

**Comment by ChShersh** [comment]
@kristoff3r You can put tests in `base@basic` folder. The separation is by used library: different libraries have different special cases. In your case you don't actually test any library, only comments. So `base@basic` is okay. `importify@project` folder contains tests for project itself to verify that `importify` can remove imports not only from dependencies but from project itself.

**Comment by kristoff3r** [comment]
I have added a test case and some handling for inline comments. My solution isn't perfect, as I use the SrcSpan from before removals, so there will be edge cases where comments are dropped (e.g. if qualified is removed, if extra spacing is added and especially if importify begins inserting extra symbols), but it should be a strict improvement.

**Comment by ChShersh** [comment]
@kristoff3r Your work looks amazing *.* Well, I don't think we should care much about general solution. Such solution will make code a lot more difficult. But I don't think it's really useful... Because I didn't see import sections with a lot of comments inside those sections.

**Pull request merged**
