### PR TITLE
Fix Travis CI

### PR DESCRIPTION
**Pull request by ChShersh**

### CODE REVIEW

**Comment by ChShersh** [comment]
@Anton-Latukha Could you please rebase onto `master` branch and update your branch? Travis failed because it tries to pass some tests which **are** in `master` but **aren't** in your branch. I don't know why it tries to do that though...

**Comment by Anton-Latukha** [comment]
If is great that you have made pull request from branch.
Learning something every day.

**Comment by Anton-Latukha** [comment]
If I understood what you've said correctly, - it is logical that PR runs against master branch, not my branch.

I rebased on the `master`

**Comment by Anton-Latukha** [comment]
Please look into build, in real:
```
test/hspec/Test/File.hs:43:

1) file:unused, subfolder: test/test-data/base@basic/, /home/travis/build/serokell/importify/test/test-data/base@basic/40-PreserveComments.hs

expected: "module PreserveComments where\n\nimport Data.Bool (Bool(..))\n-- keep this\nimport {- multiple -} qualified {- comments -} Data.List (replicate) {- on one line! -}\nimport Data.Text -- also this\nimport Control.Monad (forM_)\nimport {- B -} qualified Data.Map {- D -} as {- E -} Map {- F -} (empty)\n\n\n-- Dummy code\nmain :: IO ()\nmain = if True\n then forM_ (replicate 2 2) $ return ()\n else let m = Map.empty in return ()\n"

but got: "module PreserveComments where\n\nimport Data.Bool (Bool(..))\n-- keep this\nimport Control.Monad (forM_)\nimport {- B -} qualified Data.Map {- D -} as {- E -} Map {- F -} (empty)\n\n\n-- Dummy code\nmain :: IO ()\nmain = if True\n then forM_ (replicate 2 2) $ return ()\n else let m = Map.empty in return ()\n"
```

Looks like legitimate reproducible test failure.

**Comment by ChShersh** [comment]
@Anton-Latukha I will look into this issue today and will try to test it locally. Maybe tests are broken indeed.

**Comment by ChShersh** [comment]
@Anton-Latukha Tests were broken indeed. I fixed them. They are passing locally for me now. Let's wait for CI...

**Pull request merged**
